### ISSUE TITLE
uglify do not work

### ISSUE THREAD

**Issue by LucasBadico** [planetoftheweb/workflows#2]
Hey Ray, I'have been using your course to setup the enviroment for my actual project, everthing worked fine until here, but uglyfy isn't effect nothing on my javascritp. Alredy search for answers on stackoverflow but note clearify this... you have some directions?

**Comment by planetoftheweb** [comment]
Are you getting any errors? Maybe looking at the uglify docs would help.

**Comment by LucasBadico** [comment]
If I said to you about a "i" misplaced on the arquive path, you would belive in me? 

Well, thanks for the quick reply, and for you know:
You and Simon Alirdice on lynda.com are like my mentors on this carrer path. Your aprouch on news tools is inspiring to me. If I'm doing today very well on my projects is because of your work!

Said that, sorry for make a request for nothing!
