### ISSUE TITLE
No longer reloads when sass is updated

### ISSUE THREAD

**Issue by operapreneur** [planetoftheweb/workflows#3]
Thanks for this very helpful tutorial. 

It seems this hasn't been updated in quite some time and it no longer works as intended. Most importantly the gulp task below is out of date and no longer does an automatic reload when the sass is updated: 

`gulp.task('compass', function() {
  gulp.src(sassSources)
    .pipe(compass({
      sass: 'components/sass',
      image: 'builds/development/images',
      style: 'expanded'
    })
    .on('error', gutil.log))
    .pipe(gulp.dest('builds/development/css'))
    .pipe(connect.reload())
});`

I haven't been able to get to the bottom of the changes and it seems that there is an [issue with the gulp-livereload](https://github.com/vohof/gulp-livereload/issues/59). This is a [possible solution](http://stackoverflow.com/questions/22989009/why-doesnt-live-reload-work-with-gulp-connect) that I have not tried yet.

**Comment by planetoftheweb** [comment]
I'm marking this course for a possible update. I think the gulp process fails to reload because of a plugin upgrade. I'm currently using gulp-webserver on most courses. https://www.npmjs.com/package/gulp-webserver and that works really well.

**Comment by operapreneur** [comment]
Thanks for the resource and update. I opted for Browser Sync which seems much more robust and feature rich. https://www.browsersync.io/
