### ISSUE TITLE
does anybody known how to upgrade code for gulp 4

### ISSUE THREAD

**Issue by johnybrownalreadytaken** [planetoftheweb/workflows#9]
I am following the course but I'm using gulp 4 instead of 3
had no problems with using glup.series and gulp.parallel
but now I'm stuck with gulp-connect and livereload
it kinda works as it should but terminating process is causing some problems:

> The following tasks did not complete: default, connect
> Did you forget to signal async completion?

I know answer is somewhere here:
[Gulp error: The following tasks did not complete: Did you forget to signal async completion?](https://stackoverflow.com/questions/36897877/gulp-error-the-following-tasks-did-not-complete-did-you-forget-to-signal-async)
or here:
[LiveReload is broken ](https://github.com/avevlad/gulp-connect/issues/252)
but I can't manage to find it

```
gulp.task('css', function() {
  return gulp.src(PATH)
//...
    .pipe(connect.reload());
})
gulp.task('connect', function(done) {
  connect.server({
      root: 'builds/development/',
      livereload: true
    }), function() { this.server.on('close', done) }
});
gulp.task('watch', function(done) {
  //...
  gulp.watch(PATH, gulp.series('css'));
  done()
})

gulp.task('default', gulp.parallel('connect', 'watch'));
```

I tried modifying my watch task to look more like:
```
function watchTask (done) {
  watch('public').on('change', (filepath) =>
    src(filepath, { read: false }).pipe(connect.reload()))
  done()
} 
```

to no success..

- - - - - -

this works , just as it should (although terminating task hangs bash in vscode? but that completely unrelated issue ...)

```
gulp.task('css', function() {
  return gulp.src(PATH)
    // ..
    .pipe(connect.reload());
})

gulp.task('connect', function(done) {
  connect.server({
    root: 'builds/development/',
    livereload: true
  })
  done()
});

gulp.task('watch', function(done) {
// ..
  gulp.watch(PATH, gulp.series('css'));
  done()
})

gulp.task('default', gulp.parallel('connect', 'watch'));
```

**Comment by planetoftheweb** [comment]
Gulp 4 is totally different than Gulp 3. I've had lots of trouble with the new version, just getting things to work, so I appreciate you leaving these notes here.
